basePath: /
host: localhost:3400
info:
  contact:
    name: KhAy
  description: "The mad backend \U0001F525\U0001F525\U0001F525\U0001F525\U0001F525"
  license:
    name: MIT
  title: Creatives Quill Backend
  version: "0.1"
paths:
  /health:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      summary: Show the status of server.
      tags:
      - health
  /signin:
    post:
      consumes:
      - '*/*'
      description: to sign in user.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      summary: Signin user.
      tags:
      - health
swagger: "2.0"
